version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "1500:3000"
  backend:
    build: ./backend
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
